### ISSUE TITLE
[Feature Request] add "Select"

### ISSUE THREAD

**Issue by Ahmedazim7804** [luanon404/seledroid#10]
can you implement "Select" method from selenium.webdriver.support.ui ?
btw thanks for awesome work on this project.

**Comment by luanon404** [comment]
uh... i dont know what it use for :/ can you give me a example? and more selenium is very big so i cant code all of method so if you need something please open issues with some example or detail, thanks.

**Comment by luanon404** [comment]
do you want like this?
https://stackoverflow.com/a/45135082

**Comment by Ahmedazim7804** [comment]
> uh... i dont know what it use for :/ can you give me a example? and more selenium is very big so i cant code all of method so if you need something please open issues with some example or detail, thanks.

Yes I understand.
"select" is used to select value from dropdown or list on webpage.
one example is ( from my code ), it select all index (1 to 12 for all months) in dropdown menu on webpage, one by one and get data.

```
months = range(0, 12)
WebDriverWait(browser, 10).until(EC.invisibility_of_element((By.XPATH, "//div[@class='loader-container']")))
dropdown = Select(browser.find_element(By.NAME, "month"))
WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.XPATH, "/html/body/app/ng-component/main/sessions/div/select/option[2]"

all_months_total = 0

for index in months:
    dropdown.select_by_index(index)
    month = dropdown.first_selected_option.text
    wait_to_load()
    this_month = get_data()
    all_months_total = all_months_total + this_month
    print(f"Total Data Used in {month}: {this_month}GB")```

**Comment by Ahmedazim7804** [comment]
> do you want like this? https://stackoverflow.com/a/45135082

No, something like this 
https://stackoverflow.com/a/28613320

**Comment by luanon404** [comment]
> > do you want like this? https://stackoverflow.com/a/45135082
> 
> No, something like this https://stackoverflow.com/a/28613320

![image](https://user-images.githubusercontent.com/71830807/170276106-50305481-7e1a-4f43-9e53-2aa5303f8cf5.png)
you want select this?

**Comment by Ahmedazim7804** [comment]
> > > do you want like this? https://stackoverflow.com/a/45135082
> > 
> > No, something like this https://stackoverflow.com/a/28613320
> 
> ![image](https://user-images.githubusercontent.com/71830807/170276106-50305481-7e1a-4f43-9e53-2aa5303f8cf5.png)
> you want select this?

Yes

**Comment by luanon404** [comment]
> > > > do you want like this? https://stackoverflow.com/a/45135082
> > > 
> > > 
> > > No, something like this https://stackoverflow.com/a/28613320
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/71830807/170276106-50305481-7e1a-4f43-9e53-2aa5303f8cf5.png)
> > you want select this?
> 
> Yes

i got that please wait for new update

**Comment by luanon404** [comment]
new update [here](https://github.com/luanon404/seledroid/issues/11)
