### ISSUE TITLE
WebDriverWait return bool value instead of element

### ISSUE THREAD

**Issue by Ahmedazim7804** [luanon404/seledroid#12]
hello, In the latest version of seledroid, "WebDriverWait" function with "element_to_be_clickable" return bool value instead of the web element.

code:
```
login = WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[1]/div/div[1]/div/div[1]/div[2]/div[3]/div[3]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div[1]/a")))

login.click()
```

result:
![Screenshot_20220526-221225_Termux~2](https://user-images.githubusercontent.com/54241827/170535227-6bc22fb3-80d9-4ccb-940c-6e9b808719e9.png)

with a bit of debugging i have found a fix by changing

```
def is_disabled(self):
    return self.execute(self.command, request=Command.IS_DISABLED, element_path=self.element_path, by=self.by, value=self.value).result
```

<p align="center">to</p>

```
def is_disabled(self):
    return self.execute(self.command, request=Command.IS_DISABLED, element_path=self.element_path, by=self.by, value=self.value).result or False
```
in class "WebElement" in remote/web_element.py
like how it was in previous version.
i don't know how it affects overall code but it seem to fix the problem.

**Comment by luanon404** [comment]
hi, i remade my code and delete all **or True** in return, so error is easy, im waiting some one report so i can fix, because some javascript function return null instead of bool, i will check later, thank you.

**Comment by luanon404** [comment]
this problem happens in eval js function of webview, if you don't set disabled  as true or false it will return null, else js will return current state (true or false not null)

**Comment by luanon404** [comment]
i will add it in 1.0.7 soon.

**Comment by luanon404** [comment]
hi @Ahmedazim7804 , any update about bug? did you find any new bug?

**Comment by luanon404** [comment]
look fine i will close

**Comment by Ahmedazim7804** [comment]
> hi @Ahmedazim7804 , any update about bug? did you find any new bug?

No, i did not found any new bug, but will report if i find any.

**Comment by Ahmedazim7804** [comment]
> look fine i will close

is it fixed?

**Comment by luanon404** [comment]
> > look fine i will close
> 
> is it fixed?

yes but im testing all function again, will update soon
