### ISSUE TITLE
Please Implement "invisibility_of_element_located"

### ISSUE THREAD

**Issue by gitaccount88** [luanon404/seledroid#17]
Hi, can you please implement "invisibility_of_element_located" method from "expected_conditions". it is really useful to know if something is covering an element.
Thanks

**Comment by luanon404** [comment]
any else? i will update it later

**Comment by gitaccount88** [comment]
Other conditions will be helpful too but for right now this would be enough. Thanks

**Comment by luanon404** [comment]
too little to update, just dm my telegram i will send u that @luanon404
