### ISSUE TITLE
Error: Not found; no service started.

### ISSUE THREAD

**Issue by devicewhite** [luanon404/seledroid#18]
Image: https://i.ibb.co/Jq1KVxj/Screenshot-20220628-150528-Termux.jpg

the whole process was done correctly!
I've already installed this package several times and it never happened.
gui=True: ok, working
gui=False: Returns this error

**Comment by luanon404** [comment]
what is your chromium version?

**Comment by devicewhite** [comment]
> qual é a sua versão cromo?
1.1.0 - last version updated

**Comment by luanon404** [comment]
and seledroid?

**Comment by devicewhite** [comment]
> e seledroid?

i installed it using git so i believe it is also the latest

**Comment by luanon404** [comment]
just do
import seledroid
print(seledroid.version)

**Comment by luanon404** [comment]
i think its my mistake, I added service wapper to chromium, I will upload fixed module tomorrow

**Comment by devicewhite** [comment]
>>> import seledroid                                       >>> versíon = seledroid.version                            Traceback (most recent call last):                           File "<stdin>", line 1, in <module>                      AttributeError: module 'seledroid' has no attribute 'version'
>>>

**Comment by luanon404** [comment]
> ```
>                                      >>> import seledroid                                       >>> versíon = seledroid.version                            Traceback (most recent call last):                           File "<stdin>", line 1, in <module>                      AttributeError: module 'seledroid' has no attribute 'version'
> ```
> 
> > > >

sorry its `seledroid.__version__` not seledroid.version

**Comment by devicewhite** [comment]
Python 3.10.5 (main, Jun  7 2022, 03:53:14) [Clang 12.0.8 (https://android.googlesource.com/toolchain/llvm-project c935d99d7 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import seledroid
>>> version = seledroid.__version__
>>> print ("This version:", version)
This version: 1.0.9
![Screenshot_20220628-184102_Termux](https://user-images.githubusercontent.com/65994174/176304649-e6b808d1-26d9-4f2e-9abf-321bafcaca0a.jpg)

**Comment by luanon404** [comment]
i upload [new version](https://github.com/luanon404/seledroid/issues/19), just upgrade seledroid and chromium
