### ISSUE TITLE
How to set Desktop site in Chromium using seledroid

### ISSUE THREAD

**Issue by szuhnu** [luanon404/seledroid#20]
Hi, I have a qurey, how to set Chromium as descktop site using seledroid webdriver? Recently I access a website that will redirect to download app not to display target webpage I want to go to. If switch to the Desktop site in Chrome browser it is not the issue. Thanks.

**Comment by luanon404** [comment]
driver.user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0"

**Comment by szuhnu** [comment]
Great with thanks!
