### ISSUE TITLE
Cannot delete cookies

### ISSUE THREAD

**Issue by MR-X-junior** [luanon404/seledroid#21]
This library is very good, I really like it, but I'm having some problems using it.

I have Python code like this.

```python
>>> from seledroid import webdriver
>>> web = webdriver.Chrome()
>>> web.get("https://mobile.facebook.com")
```

So far there has been no problem.

Then I try to fetch cookies on webdriver

```python
>>> web.get_cookies()
'datr=xxxxxxx; sb=xxxxxxxxx; m_pixel_ratio=2; wd=360x679; fr=xxxxxxxxxxxx'
```

But when I try to delete all cookies in webdriver, it doesn't work at all 

```python
>>> web.clear_cookies()
>>> web.get_cookies()
'datr=xxxxxxx; sb=xxxxxxxxx; m_pixel_ratio=2; wd=360x679; fr=xxxxxxxxxxxx'
```

Can you help me?:)

**Comment by luanon404** [comment]
because i use js to make that cookie out of date, but some sites like fb, maybe prevent to execute js to change cookie or the library too old.

**Comment by luanon404** [comment]
if you interested, you can try selenium while waiting me finish new webdriver

**Comment by luanon404** [comment]
https://github.com/luanon404/Selenium-On-Termux-Android/

**Comment by MR-X-junior** [comment]
> https://github.com/luanon404/Selenium-On-Termux-Android/

I've installed selenium with version `4.9.1` on my termux app, and it worked. But where can I get a chrome webdriver that supports the Termux application?
