### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by m00n-err0r** [luanon404/seledroid#8]
How can I set http or socks proxy?

**Comment by luanon404** [comment]
yes but when i try it it seems quite laggy, i will add it later

**Comment by m00n-err0r** [comment]
Sounds good. Can you guess how long it will take you to add the functionality?

**Comment by luanon404** [comment]
oh sorry i forgot that just take ≈ 15-20 minutes i will do now 😅

**Comment by m00n-err0r** [comment]
Awesome, I look forward to it)

**Comment by luanon404** [comment]
tomorrow i will do that now is 2am, sorry but i need to sleep :((

**Comment by m00n-err0r** [comment]
Alright, good night)

**Comment by luanon404** [comment]
> Alright, good night)

i added at [here](https://github.com/luanon404/seledroid/issues/9)
